import streamlit as st
from datetime import datetime
import plotly.graph_objects as go
#import pyttsx3
import anthropic
import json
from typing import List, Dict
import random
import time
import os
#####################################         INTERVIEW DATA FILE         ###################################################

INTERVIEW_DICT={
    "interviews": [
        {
            "interview_id": "GEST001",
            "topic": "Zomato Revenue Estimation",
            "exchanges": [
                {
                    "role": "interviewer",
                    "content": "Your problem statement is to calculate the revenues generated by Zomato. Please feel free to ask any clarifying questions before you begin."
                },
                {
                    "role": "candidate",
                    "content": "Are we considering a weekday or weekend?"
                },
                {
                    "role": "interviewer",
                    "content": "Weekend. So why is this question related?"
                },
                {
                    "role": "candidate",
                    "content": "Sundays, the order might be high. Because those are holidays"
                },
                {
                    "role": "interviewer",
                    "content": "Okay, so what you can do is you can just consider it as a normal weekday."
                },
                {
                    "role": "candidate",
                    "content": "are we talking about any particular geographical area? Or are we talking about whole India."
                },
                {
                    "role": "interviewer",
                    "content": "whole India."
                },
                {
                    "role": "candidate",
                    "content": "So the problem statement is we have to calculate the revenues zomato on a normal day. And we have to calculate the revenue of the whole India. Is that right? Yeah, so can I take a minute to frame the The answer."
                },
                {
                    "role": "interviewer",
                    "content": "Yeah Yeah. So you don't have any other questions. Right?"
                },
                {
                    "role": "candidate",
                    "content": "I think. that would be enough, I guess."
                },
                {
                    "role": "interviewer",
                    "content": "Okay, so what you can do is just take five to six minutes. what I want from your side is just the approach. I don't want numbers right now. Just the share that approach to me. we can talk about it and then if I'm in line with the approaching and then we can  go to numbers, so this is what we'll do. So you can take your time."
                },
                {
                    "role": "candidate",
                    "content": "Okay, so I'm ready with my approach. We will take the Indian population, then divided in urban population, and rule population. so assuming that as a matter of fact zomatomajorly operates in urban cities in urban population. So, After that, we will take in account the penetration of the active Internet users in urban population. So after that we would be estimating the age group that might be using zomato the most ."
                },
                {
                    "role": "interviewer",
                    "content": "How does age group matter in this question?"
                },
                {
                    "role": "candidate",
                    "content": "Of course, the Zomato has to do with smart devices, using some matter has to do, with smart devices, and Internet usage. And I guess the people above 18 and under 60 are most actively. Using a small devices, and they are the potential customers of the matter."
                },
                {
                    "role": "interviewer",
                    "content": "Okay, anything else age influences here? According to you?"
                },
                {
                    "role": "candidate",
                    "content": "Yes, because ordering from zomato use a kids. Don't usually order from the matter on their own. In generally, their parents order for them for their family. And after that, we would be taking in around the market share of the matter in this particular age group. And then In this question, we have to estimate the revenue on a normal day. So, first of all, I would like to ask that. Are we talking about the market share or the amount in a revenue rupees?"
                },
                {
                    "role": "interviewer",
                    "content": "Yeah, the amount in  Indian rupees"
                },
                {
                    "role": "candidate",
                    "content": " Okay, so after estimating the market share, We would take the medium users, and low users. and then, estimate, the average order value, and then multiply the respective numbers and then we can say, we have calculated the estimated revenue of the matter on a day on a normal day that big"
                },
                {
                    "role": "interviewer",
                    "content": "But how would you calculate for a day like you do this? How would you know that the number of orders in a day, are this or that."
                },
                {
                    "role": "candidate",
                    "content": "using the frequency of orders of user,\u00e2\u20ac\u00a6assuming that high frequency users usually orders 30 times in a month and a medium users, usually Orders, 15 times a month, and a low user usually orders for two \u00e2\u20ac\u201c three times a month. So taking on an average, we would take how that market size population. multiplying that by the average order value will be able to decide the Revenues in a month."
                },
                {
                    "role": "interviewer",
                    "content": "Okay. from what sources does zomato make revenues according to you? What are the other sources according to you?"
                },
                {
                    "role": "candidate",
                    "content": "The sales of zomato premium. And zomato in & out."
                },
                {
                    "role": "interviewer",
                    "content": "Yeah, And do you think you missed any filter? In the approach. Anything that should be relevant for the purpose of the question"
                },
                {
                    "role": "candidate",
                    "content": " I guess I have covered all of it."
                },
                {
                    "role": "interviewer",
                    "content": "What about the household filter?"
                },
                {
                    "role": "candidate",
                    "content": "Ohh !  okay , yes. "
                },
                {
                    "role": "interviewer",
                    "content": "It might be relevant, Why do you think that? "
                },
                {
                    "role": "candidate",
                    "content": "yes, it is  because, Usually people don't order for themselves. Only, they order for a group of three, four people. So, we have to make\u00e2\u20ac\u00a6 how household in the account."
                },
                {
                    "role": "interviewer",
                    "content": "): So I guess we can also incorporate that, Okay,\u00e2\u20ac\u00a6 so I think more or less the approach looks. Alright, while I'm hearing it. So maybe let's just go to the numbers and calculate something, right? So in proceed and start."
                },
                {
                    "role": "candidate",
                    "content": "Okay, for start, we will take the population of India to be 140 million 140."
                },
                {
                    "role": "interviewer",
                    "content": "okay, 14. 0 billion is population India . Is it ?14  billion?"
                },
                {
                    "role": "candidate",
                    "content": "1.4 billion. I'm sorry. Yes.Yeah, let's say 4: 7 urban to rural ratio in this population.and with the urban population, we can assume that 400 million people to be of urban population."
                },
                {
                    "role": "interviewer",
                    "content": " Okay , go ahead. so it's 70% is rural. Then what does rural no. give me according to these numbers. And if 30% is urban, then what will that give me?"
                },
                {
                    "role": "candidate",
                    "content": "Roughly around 1 billion. People are rural India."
                },
                {
                    "role": "interviewer",
                    "content": "One billion. Okay, alright, 1 billion people in rural India and how much in urban"
                },
                {
                    "role": "candidate",
                    "content": "We can take 400 million, we can take the difference."
                },
                {
                    "role": "interviewer",
                    "content": "Let's just talk in crores .So yeah, 40 crores in urban and 100 crores in rural, right? Okay"
                },
                {
                    "role": "candidate",
                    "content": "Yeah , Okay"
                },
                {
                    "role": "interviewer",
                    "content": "what next?"
                },
                {
                    "role": "candidate",
                    "content": "We will take an account. The. urban household total household. So We are assuming that every household has an on average 4 people. So, We have 100 million households."
                },
                {
                    "role": "interviewer",
                    "content": "100 million. Ten croes, right?",
                    "context": ""
                },
                {
                    "role": "candidate",
                    "content": "Yes. Yes,  assuming that every house and assuming that, 95% of the household has penetration and access to Internet."
                },
                {
                    "role": "interviewer",
                    "content": "95% of them have access to Internet penetration. How do you make that "
                },
                {
                    "role": "candidate",
                    "content": " Okay, we might take by Internet penetration. I was meaning that 80% of the households, have some smart devices Access to them."
                },
                {
                    "role": "interviewer",
                    "content": " Again, how do we make that assumption. Any logical reasoning for this percentage?"
                },
                {
                    "role": "candidate",
                    "content": " In urban population, we have high income households we have medium income household upper income households and low income houses. So I'm assuming the low income households More than 50% of them don't have access to smart devices."
                },
                {
                    "role": "interviewer",
                    "content": "Can you just segment for me? what percentage would you give to the low income households?"
                },
                {
                    "role": "candidate",
                    "content": "So, we have 40 crore urban population and I would take in account,\u00e2\u20ac\u00a6 10% of the people are High income households. 60% of the people are. Middle income households. That would leave low income by  20%."
                },
                {
                    "role": "interviewer",
                    "content": "You listed many classes. Can you just repeat again?let's just back up. We had 40 crore people, right? And then we use a high household filter saying that four people would be living in my house, right? So that gave me 10 crore household, so yeah, Now, you do the bifurcation of income. "
                },
                {
                    "role": "candidate",
                    "content": "So then we pocketed in three categories, upper, middle income households and low income  and I further biffurcate , the middle income households in upper middle category and lower income"
                },
                {
                    "role": "interviewer",
                    "content": "You did not communicate that properly. Okay."
                },
                {
                    "role": "candidate",
                    "content": "Okay, okay. So I'm assuming that all the higher class, people have the Internet when you get them penetration and so The 20% upper middle class and the rest, 70% of the people that includes the lower middle class and the low class income household. I'm assuming, that 60% of them would have a smart devices penetration. "
                },
                {
                    "role": "interviewer",
                    "content": "60% of the lower class, What do you mean by workers? "
                },
                {
                    "role": "candidate",
                    "content": "I am assuming that daily wage workers in urban cities that are earning less than 20,000. In a household in a family."
                },
                {
                    "role": "interviewer",
                    "content": "All right, and you think that 60%, Would be able to buy a smartphone"
                },
                {
                    "role": "candidate",
                    "content": "60% of of lowering lower middle class and the low class."
                },
                {
                    "role": "interviewer",
                    "content": "Okay, why do you think 40% of them would not be able to buy smartphones. What is the reason according to you?"
                },
                {
                    "role": "candidate",
                    "content": "First of all, the price of phone a basic smartphone starts from, 10,000 or 8,000 and I guess the priority of low-income households before mobile phone would be meeting their daily needs their ration and all and so"
                },
                {
                    "role": "interviewer",
                    "content": "Okay, That is fine. So we had 10 crore households and if we take this all into account that you just said that these many people in all different classes would be able to buy now. Maybe you can suggest a percentage of how much would be able to buy smartphones or would have in Internet penetration. So what that percentage would be"
                },
                {
                    "role": "candidate",
                    "content": " Okay, so, as I said earlier, The low income household and the low middle class households. 60% of them would be having smartphone devices. So 40 % here. And So around, roughly, 75% of the urban population. would have access to smartphone devices, and so they are the potential customers of zomato and"
                },
                {
                    "role": "interviewer",
                    "content": "Okay"
                },
                {
                    "role": "candidate",
                    "content": "Yes, and talking about the market share. And No in 70% households and The total 70% of unpopulation"
                },
                {
                    "role": "interviewer",
                    "content": "No, no, you don't like Key. 70% would be the ones who would have smartphones, right?"
                },
                {
                    "role": "candidate",
                    "content": "Seven crore. I have wriiten my answer in millions , so i got confused"
                },
                {
                    "role": "interviewer",
                    "content": "No issues. Alright, so you get the number seven crore. What do you do next?"
                },
                {
                    "role": "candidate",
                    "content": ": So bifurcating the target or audience, so For example, then approaching toward the market share of the matter. So I'm assuming that market share of the matter.so there are seven crore Smartphones or seven crude households. That would have that crystal smartphones.So I'm assuming that they all are the potential customers of zomato, they might be ordering each once in a while from zomato. because, The.The penetration of the zomato or the penetration of online ordering business at is very common in urban cities. So I must hold of that 70% of the urban households are the potential customers of online food,\u00e2\u20ac\u00a6delivering businesses. So"
                },
                {
                    "role": "interviewer",
                    "content": "So you think zomato holds 100% market share in only for delivering."
                },
                {
                    "role": "candidate",
                    "content": "No, no. I am for dividing the market further, assuming the market share of zomato."
                },
                {
                    "role": "interviewer",
                    "content": "Okay, that does potential customer. Use you mean to say, Okay"
                },
                {
                    "role": "candidate",
                    "content": "the potential customers of zomato the online, food is delivering businesses like seven crowd households. So further approaching to the estimation. We assume that zomatoes 40% of the market share. Although there are only two major players association zomato and swiggy "
                },
                {
                    "role": "interviewer",
                    "content": " Why do you say 40?"
                },
                {
                    "role": "candidate",
                    "content": "they might be Competition. Like you know \u00e2\u20ac\u201c Swiggy , Uber Eats, Zepto and etc.believe in all so we can take an assumption that zomato\u00e2\u20ac\u2122s 40% of the market here. So it is around 2.8 crores. Households."
                },
                {
                    "role": "interviewer",
                    "content": "Yeah, 2.8 code. Let's take three crore now. You may proceed now."
                },
                {
                    "role": "candidate",
                    "content": "So, three crore are the targeted zomato customer. So we divide into are power users, that order from them and the mediums And the low users that once in a while order from zomato. So  So I would split them in the power users would be like they order from the matter at least 15 to 20 times a month."
                },
                {
                    "role": "interviewer",
                    "content": "Power users. Only order 15 to 20 times."
                },
                {
                    "role": "candidate",
                    "content": "it is a big number I guess, because I'm assuming that "
                },
                {
                    "role": "interviewer",
                    "content": "I think they should be ordering every day. Don't you think that? Because I feel like some people are, of that sort that they don't have, basis for making food by themselves and they have their income with them that they can order from online food services. So I don't think so. ordering every day is I mean, it might be a little crazy but yeah, it's a very low chunk of population that will do that. So, I guess if you are taking this as the ceiling of users, then I think we can take a higher number in this."
                },
                {
                    "role": "candidate",
                    "content": "Okay, so we take 30 orders per month as a power user and for the medium users I take 10 to 15 orders per month. And for the low users,\u00e2\u20ac\u00a6: I take two to three orders per month. so, for the bypassing categories I would Bifurcate the three crore households that I said zomato targets and\u00e2\u20ac\u00a610% them would be power users. that 60% of them would be medium users. : And the low kind of users would be 30% of the total. "
                },
                {
                    "role": "interviewer",
                    "content": "so by this, you'll get your number of orders, can you just explain me in a month?"
                },
                {
                    "role": "candidate",
                    "content": "Yeah, in a month."
                },
                {
                    "role": "interviewer",
                    "content": " Can you just explain me What will you do next?"
                },
                {
                    "role": "candidate",
                    "content": "So firstly for simplification, I woulddo that -  total number of zomato orders in a month and divide them by 30. So we have the roughest,\u00e2\u20ac\u00a6 you know how much We have daily orders from zomato, so,"
                },
                {
                    "role": "interviewer",
                    "content": ": All I think I don't want you to calculate that. Can you just tell me? do you think you missed anything depending upon what you told me earlier?"
                },
                {
                    "role": "candidate",
                    "content": "Okay, yes, I guess I approached the question very fast. I should have taken a pause and asked clarifying questions that you in the middle. said that the revenue sources of the matter that,"
                },
                {
                    "role": "interviewer",
                    "content": "No, no I'm not asking what mistakes you did any filter you missed according to In the approach.When we are doing the numbers, did you miss anything that we talked about when we were talking the approach, actually,"
                },
                {
                    "role": "candidate",
                    "content": "as for now I guess I have covered almost like,\u00e2\u20ac\u00a6"
                },
                {
                    "role": "interviewer",
                    "content": "What about the age?"
                },
                {
                    "role": "candidate",
                    "content": "yes, I did not consider the age factor because I have"
                },
                {
                    "role": "interviewer",
                    "content": "Don't you think ordering from outside? Depends, very much on your age. if you're something you might be ordering from outside,\u00e2\u20ac\u00a6"
                },
                {
                    "role": "candidate",
                    "content": "Yes, so I have not bifurcated on the H factor because I have taken in account with the household factor. So, in a house,"
                },
                {
                    "role": "interviewer",
                    "content": "But yeah, but don't do thing in India. You would have young holds old house. So your old people are living, there could be households where you have a mother and you have a father and then you have teenage daughter daughter and I don't know children, there could be household where there are, to old people that are living and then they 40. 30 days are high, right? So you could have done something around these lines because I feel such a household. The age will really depend the frequency with you, with you, with which you will order. So, age is something that you should have a bright or could have applied in this one because it's very logical that. If we are young, we tend to order more, right? Yeah,\u00e2\u20ac\u00a6"
                },
                {
                    "role": "candidate",
                    "content": "so that is a very valid point but because for the sake of simple simplicity, I forget them into the household and assume that the inner household, there are Varying varieties of age group."
                },
                {
                    "role": "interviewer",
                    "content": "Okay. What do\u00e2\u20ac\u00a6 you think average order value would be "
                },
                {
                    "role": "candidate",
                    "content": "so, the average order value would be Like adding the delivery cost and all would be around 300."
                },
                {
                    "role": "interviewer",
                    "content": "I think. Alright, for two people or for one? Because I'm here during that they're not ordering from themselves.They're obviously ordering for at least, one more person at least two I\u00e2\u20ac\u00a6And If you order for a person in zomato, what do you think the cart value is? For a person for a single person."
                },
                {
                    "role": "candidate",
                    "content": " So, the figure that I came upon 300 that is the average of people ordering from themselves. People ordering for two people and the person ordering for four people. So, as an average and the frequency, I came to a number 300 So three."
                },
                {
                    "role": "interviewer",
                    "content": " But then minimum is 300 c. You understand, the average is always the middle of a minimum or\u00e2\u20ac\u00a6maximum, So I think when you order from zomato you easily get a bill of 252 to 300 easily simple you just order something. And then, Yeah, they add up a piece of that. Just because your minimum order value or something like you, distance and everything like that. So, it's 300, minimum pressure and no matter and swiggy every food delivery app, and it goes up till to 2 to 3000 if you're ordering for more people. So maybe, little high number. Then this could be a better explanation for the average part that you've taken. So yeah. So I guess maybe close to 500 600 because if you order for two people easily, you will get something like this. Say so foreign 500 should be a better number,\u00e2\u20ac\u00a6"
                },
                {
                    "role": "candidate",
                    "content": "Okay.  That's now I don't think so I have list anything. Hey there might be some points that I have missed\u00e2\u20ac\u00a6"
                },
                {
                    "role": "interviewer",
                    "content": "I think this would be a good point to end the guest event. Mark and go to the feedback. Is that fine? Or do you have something else to add?Again, your guesstimate mock ends here."
                },
                {
                    "role": "candidate",
                    "content": "Alright."
                },
                {
                    "role": "interviewer",
                    "content": "Now for the Feedback part. for the sake of this question, I would not be considering rural areas why? Because I feel zomato's penetration. rural areas is very low and there is a general trend that in rural area areas. People don't prefer to order from outside. Maybe they just want to go outside and eat or maybe they just prefer their home household food, So They prefer going outside but they don't prefer ordering from outside because it is also you do cultural reasons that it is not normal there right now if you consider to the urban and urban counterpart, So, Be considering rural, I would be going ahead with the urban part. Population household, urban rural gender age income, penetration over at the Internet, access or language. if it doesn't say questions at all over the filters . And just a question is completely, and you'll be too to maybe potentially miscarried that I do common filters. At least because common filters,\u00e2\u20ac\u00a6"
                },
                {
                    "role": "candidate",
                    "content": "Thanks for the review and advice"
                }
            ]
        },
        {
            "interview_id": "GEST002",
            "topic": "Delhi Cigarette Smokers Estimation",
            "exchanges": [
                {
                    "role": "candidate",
                    "content": "Start",
                    "context": " Candidate indicates to start the interview"
                },
                {
                    "role": "interviewer",
                    "content": "Your problem statement is that you have to calculate the total number of people that smoke cigarettes in delhi.",
                    "context": " Interviewer presents a guesstimate problem to the candidate"
                },
                {
                    "role": "candidate",
                    "content": "So in this question are we considering any particular category of cigarettes?",
                    "context": " Clarifies the question"
                },
                {
                    "role": "interviewer",
                    "content": "Yes, calculate for tobacco cigarettes",
                    "context": " Interviewer randomly selects what he wants the candidate to focus on"
                },
                {
                    "role": "candidate",
                    "content": "Do we have do consider cigarettes as preminum or cheap ones?",
                    "context": " Clarifies the question"
                },
                {
                    "role": "interviewer",
                    "content": "Calculate for premium",
                    "context": " Interviewer randomly selects what he wants the candidate to focus on"
                },
                {
                    "role": "candidate",
                    "content": "So to tackle this problem, we would start with the delhi population of 2 crore",
                    "context": " To takle problem establised in step -1 starting by the population is always a good starting point since our answer would be subset of the overall population of delhi. hence as the candiate starts with this and states that the delhi population as 2 crores"
                },
                {
                    "role": "interviewer",
                    "content": "Alright.",
                    "context": " Candidate starting point is correct and the number stated is also correct"
                },
                {
                    "role": "candidate",
                    "content": "Then i would be bifurcating delhi population on the basis of age",
                    "context": " Proceeds to narrow down the population of 2 crores established in step 1 by suggesting age as a specefic filter because proneness to smoking correlates to age"
                },
                {
                    "role": "interviewer",
                    "content": "Why do you do the age segmentation?",
                    "context": " Understands the logic presented and delebrately questions the assumptions presented"
                },
                {
                    "role": "candidate",
                    "content": "I did the age segmentation because your prone to smoking a cigarette would be a factor of your age, since as your age increases people are less likely to smoke due to health, responsiblities etc.",
                    "context": " Provides a logical reason for using age as a specefic filter"
                },
                {
                    "role": "interviewer",
                    "content": "Ok, go on..",
                    "context": " Shows his agreement since the reason is logical"
                },
                {
                    "role": "candidate",
                    "content": "18 to 60 would be the targeted segment that will smoke",
                    "context": " Age is establised as a filter in step 3 so candidate chooses a particular age segment between 0 to 70 years."
                },
                {
                    "role": "interviewer",
                    "content": "Why this particular target segment?",
                    "context": " Tests why did the candidate choose this particular segment to unserstand his reasnoning."
                },
                {
                    "role": "candidate",
                    "content": "So, because people under the age of 18, don't tend to smoke cigarettes as much and people above age of 60 are health conscious and their health restrictions force them to leave cigarettes.",
                    "context": " Provides a logical reason for choosing a specefic age segment to narrow down the population established in step 1"
                },
                {
                    "role": "interviewer",
                    "content": "Alright.",
                    "context": " Shows his agreement since the reason is logical"
                },
                {
                    "role": "candidate",
                    "content": "Then further i would be dividing the age groups, 18 to 30 and 30 to 60.",
                    "context": " Divided the selected age segment establised in step 5 into two groups."
                },
                {
                    "role": "interviewer",
                    "content": "Why did you specefically segment 18 to 60 into 2 buckets being 18 to 30 and 30 to 60",
                    "context": " Delibrately questions on why did the candidate segment like this to understand his reasoning."
                },
                {
                    "role": "candidate",
                    "content": "I did this because when a person is in the age group of 18 to 30, they are more prone to smoking cigereetes as they are healthy and have less respponsibilty while as there as their age increases they become more responsible and less healty hence a less percentage will be prone in older ages.",
                    "context": " Provides a logical reason for choosing the sub segments suggested in step 6"
                },
                {
                    "role": "interviewer",
                    "content": "Ok",
                    "context": " Shows his agreement since the reason is logical"
                },
                {
                    "role": "candidate",
                    "content": "Now as stated since the delhi's population is 2 crore, since india is a young nation 40% of the population will fall in 18 to 30 while another 40% of the population will fall in 30 to 60, that will be 80 lakhs for both groups",
                    "context": " Proceeds to narrow down the population establised in step 1 into sub segments establised in step 7"
                },
                {
                    "role": "interviewer",
                    "content": "Alright.",
                    "context": " Shows his agreement since numbers assumed by the candidate are logical and the final numbers are correct for both age sub segments after calculations."
                },
                {
                    "role": "candidate",
                    "content": "And as stated in my assumption that the people smking in order ages will be less, i will be considering that 60% of the people in 18 to 30 and 40% of the people in 30 to 60 will be prone towards smoking, hence giving us 48 lakh and 32 lakh respectively.",
                    "context": " Calculates the population prone to smoking in each age sub segment"
                },
                {
                    "role": "interviewer",
                    "content": "Alright.",
                    "context": " Shows his agreement since numbers assumed by the candidate are logical and the final numbers are correct for both age sub segments after calculations."
                },
                {
                    "role": "candidate",
                    "content": "Hence a total of 80 lakh people are prone towards smoking",
                    "context": " Adds the numbers calculated in the step 9 and calculates a total."
                },
                {
                    "role": "interviewer",
                    "content": "Ok",
                    "context": " Shows his validation."
                },
                {
                    "role": "candidate",
                    "content": "To further calculate the total no. of people actually smoking i will segment this 80 lakhs on the basis of gender.",
                    "context": " Proceeds to narrow down the population established in step 10 by suggesting gender as a specefic filter because proneness to smoking correlates to gender in india"
                },
                {
                    "role": "interviewer",
                    "content": "Why segmenting on the basis of gender relevent here?",
                    "context": " Delebrately tests why did the candidate do this gender segmentation to understand his reasoning."
                },
                {
                    "role": "candidate",
                    "content": "Since in india men seem to smoke more as compared to females.",
                    "context": " Provided a logical reason for using gender as a possible filter"
                },
                {
                    "role": "interviewer",
                    "content": "Alright go on.",
                    "context": " Shows agreement"
                },
                {
                    "role": "candidate",
                    "content": "So considering a 50/50 split there would be 40 lakh males and 40 lakh females",
                    "context": " Proceeds to segment gender established in step 12 into two sub segments and calcuates the population in each sub segment"
                },
                {
                    "role": "interviewer",
                    "content": "Ok",
                    "context": " Shows his agreement since it looks logical"
                },
                {
                    "role": "candidate",
                    "content": "Considering 60% of the men smoke cigarettes and 20% of the females smoke, we will get a total no. of 32 lakh smoking population.",
                    "context": " Proceeds to calcuate the smoking population in two sub segments established in step 13 and their total"
                },
                {
                    "role": "interviewer",
                    "content": "Ok",
                    "context": " Shows his agreement since the numbers are correct and logical"
                },
                {
                    "role": "candidate",
                    "content": "And then, since this question we have to find out the number of people who smoke premium cigarettes. we will further bifocate this smoking population into income groups and consider which groups can afford premium cigarettes",
                    "context": " Provided his reasoning for applying the income filter since it was establised at step 0 by the interviewer to calculate for premium cigarettes."
                },
                {
                    "role": "interviewer",
                    "content": "Alright.",
                    "context": " Shows his agreement since interviewwer establised the same at step 0"
                },
                {
                    "role": "candidate",
                    "content": "I will bifurcate into 4 income groups that are below poverty line, lower middle class, upper middle class and upper class. with 20% , 40%, 30% and 10% respectively",
                    "context": " Segments the income filter establised in step 15 into four sub segments on the basis of their income with below povery line being the lowest and upper class being the highest"
                },
                {
                    "role": "interviewer",
                    "content": "Go on..",
                    "context": " Shows his agreement since the disctribution stated by the candiate is standard."
                },
                {
                    "role": "candidate",
                    "content": "And for the purpose of premium cigarettes i will be considering that only upper middle class and upper class would be able to afford those.",
                    "context": " Isolates highest and second highest income groups from the 4 sub sugments established in step 16 since they will be able to afford premium cigarettes"
                },
                {
                    "role": "interviewer",
                    "content": "Ok",
                    "context": " Shows his agreement since the logic is correct and the calcualtions are also correct."
                },
                {
                    "role": "candidate",
                    "content": "Upper middle class are 30% of 32 lakhs and upper class are 10% of 32 lakhs hence giving us a total of 13 lakhs approx",
                    "context": " Proceeds to narrow down the popuation calculated in step 14 into the two isolated sub segments establised in step 17 on the basis of their weightages and calculates the total"
                },
                {
                    "role": "interviewer",
                    "content": "Alright, go on",
                    "context": " Shows his agreement since the logic is correct and the calcualtions are also correct."
                },
                {
                    "role": "candidate",
                    "content": "Now 13 laks is the premium cigarette smoking population of delhi but since we have to calculate for tobacco ciggertes, we would further segment this popuation into categories of ciggertes they smoke.",
                    "context": " Proceeds to narrow down the population cacluated in step 18 on the basis of category of cigarette establied in step 0"
                },
                {
                    "role": "interviewer",
                    "content": "Ok",
                    "context": " Shows his agreement since the category was previously establised in step 0."
                },
                {
                    "role": "candidate",
                    "content": "Different categories would be tobacco and non-tobacco",
                    "context": " Proceeds to suggest two different sub segments for the category filter established in step 19"
                },
                {
                    "role": "interviewer",
                    "content": "Ok",
                    "context": " Shows his agreement since segmentation is logical."
                },
                {
                    "role": "candidate",
                    "content": "And for the purpose of this question we will be focusing on tobacco cigarettes as clarified earlier at the start",
                    "context": " Proceeds to isolate tobacco sub segment as established in step 0"
                },
                {
                    "role": "interviewer",
                    "content": "Alright go on.",
                    "context": " Shows his agreement since segmentation is logical."
                },
                {
                    "role": "candidate",
                    "content": "Since most of the people smoke tobacco ones i would be taking 60% of 13lakhs soking tobacco cigarettes. hence we get a toal of 8 lakh people smoking premium tobacco cigarettes in delhi",
                    "context": " Proceeds to narrow down the popuation established in step 18 accross the isolated sub segment establised in step step 21 on a logical weightage"
                },
                {
                    "role": "interviewer",
                    "content": "Alright, and this is where your approach will end?",
                    "context": " Shows his agreement and asks if this will be the last step of his approach because candiate calcuates for what he was asked for at the start."
                },
                {
                    "role": "candidate",
                    "content": "Yes",
                    "context": " Responds with a agreement"
                },
                {
                    "role": "interviewer",
                    "content": "Ok, thanks.",
                    "context": " Closes the interview."
                }
            ]
        }
    ],
    "problem_statements": [
    "Estimate number of office chairs sold in India",
    "What's the market size of automotive batteries and its margins in India?",
    "Distance between New York and Delhi",
    "How many red coloured Swift cars in Delhi",
    "How many t-shirts are sold by ecommerce companies per day",
    "How many cows are there in India",
    "Number of weddings in a year in India",
    "How many golf/footballs fit in Boeing 747",
    "How many flights take off in a single day",
    "How many babies will be born next year",
    "Calculate number of napkins used in Taj Hotel",
    "Estimate total length of roads in Delhi",
    "Size of tourism industry in Kerala",
    "How many kg of paint are used in Delhi?",
    "Market size of the apparel industry",
    "Annual income of a pickpocketer in Delhi Mall",
    "Passengers travelling in the Delhi metro",
    "Street lights in India",
    "Smartphones sold per year in India",
    "Calculate the number of bricks in a building",
    "Annual demand for natural gas in India",
    "Cabs in Delhi",
    "People in IGI Airport daily",
    "How many fish are there in world seas",
    "Litres of petrol sold at a petrol pump daily",
    "How many words in the daily edition of TOI",
    "How many people wear red on a day in a city",
    "Diaper market in India",
    "Number of cars crossing Delhi-Gurgaon toll",
    "Revenue of a petrol pump",
    "CCTV cameras in the city",
    "ATMs in the city",
    "TVs/ACs/fridges",
    "Number of paracetamol tablets sold per day",
    "Roses on Valentine's Day",
    "Hair on your scalp",
    "Daily footfall of Delhi Airport",
    "Lenses market",
    "Number of litres of petrol used in Delhi",
    "Gurgaon toll booth revenue",
    "Estimate the number of dogs in Delhi",
    "Estimate the number of lenses manufactured in India",
    "Estimate the quantity of sauce manufactured annually in Europe",
    "Estimate the number of TVs manufactured in India",
    "Estimate the number of super-speciality hospitals in Delhi",
    "Estimate the number of CCTVs in any city other than Delhi/Gurgaon",
    "Estimate the number of Band-Aids sold in India",
    "Estimate the number of planes at Delhi Airport",
    "Estimate the number of iPhones sold in India",
    "Estimate the number of rakhis sold online",
    "Number of electricity bulbs in India",
    "Estimate tennis balls sold in India",
    "Market size of the apparel industry",
    "Estimate the litres of cola sold daily in Delhi",
    "Estimate the number of denims sold in India per year",
    "Estimate the number of red lights in Delhi",
    "Estimate the number of Economist readers in India",
    "Number of condoms sold daily in India",
    "Size of the beer market in the US",
    "Pollution emitted in Delhi",
    "Number of OYO rooms occupied on a particular day",
    "Number of Chloromint candies sold per day",
    "Potential AC market in India",
    "Number of Hajmola eaten per day",
    "Helmets sold every year in India",
    "Surface area of the plane Boeing 757",
    "Estimate sales of Domino's/Pizza Hut",
    "Total power requirement of India",
    "Number of wooden articles in your college",
    "Number of chewing gums consumed in India",
    "Monthly revenue of your hair salon",
    "How many trees are in New Delhi",
    "How many coffee cups were consumed last week?",
    "Estimate the number of hours air conditioners are run in Delhi per year",
    "Estimate the revenue from hotels and lodges in Goa",
    "Estimate average distance run by a footballer in a match",
    "Estimate the number of movies released in India per year",
    "Estimate the number of videos streamed on YouTube in Delhi on a given day",
    "Estimate the amount of data in GB of internet used on a single day in India",
    "Estimate the amount Delhi spends on street food",
    "Estimate the revenue of Haldiram's food chain in India in a single day",
    "Estimate the number of SRK fans in India",
    "Number of cars crossing the Delhi-Gurgaon toll in a day",
    "Revenue of a typical petrol pump in Delhi",
    "Number of burgers sold by a McDonald's outlet",
    "Number of CCTV cameras in a city",
    "Number of ATMs in a city",
    "Number of TVs/Refrigerators/ACs",
    "Number of paracetamol tablets sold",
    "Number of iPhones sold in India",
    "Fleet size of an airline",
    "Number of roses sold on Valentine's Day",
    "Number of footballs sold in India",
    "Number of children attending 10th/12th class/college in India",
    "Length of the road in a particular region",
    "Number of golf balls that fit the room you are sitting in",
    "Number of hair on your scalp",
    "Amount of paint required to paint this room"
]
,
    "metadata": {
        "context": "India",
        "interview_type": "Guesstimate",
        "data_version": "1.0"
    }
}




#######################################################################################
## Chatbot Class
class GuesstimateChatbot:
    def __init__(self, api_key: str):
        self.client = anthropic.Anthropic(api_key=api_key)
        self.interview_data = self.load_interview_data(INTERVIEW_DICT)
        self.conversation_history = []
        self.evaluation_criteria = [
            "Structured Approach",
            "Logical Assumptions",
            "Segmentation Strategy",
            "Mathematical Accuracy",
            "Context Awareness"
        ]
        
        # Initialize system prompt
        self.system_prompt = self.create_system_prompt()
        
    # def load_interview_data(self, file_path: str) -> Dict:
    #     """Load and parse interview data from JSON file"""
    #     with open(file_path, 'r') as f:
    #         return json.load(f)
    def load_interview_data(self, input_data) -> Dict:
        """
        Load and parse interview data.
        Accepts either a JSON string or a Python dictionary.
        """
        if isinstance(input_data, str):  # If input is a JSON string
            return json.loads(input_data)
        elif isinstance(input_data, dict):  # If input is already a dictionary
            return input_data
        else:
            raise ValueError("Invalid input: expected a JSON string or a dictionary.")
    
    def create_system_prompt(self) -> str:
        """Create system prompt for guesstimate interviews"""
        prompt = """You are an expert interviewer specializing in guesstimate questions. Your role is to:

Filters that can be used in problem for approaching problem :

   - Demographics: Age, gender, income level 
   - Geography: City, region, urban vs. rural 
   - Behavior: Usage frequency, product preference, online vs. offline activity 
   - Socioeconomic factors: Education level, occupation
   - Population segmentation
   - Regional variations
   - Income levels
   - Behavioral patterns
   - Seasonal factors


Follow these guidelines:
1. Start with a clear problem statement.
2. Let Candidate Ask clarifying questions about their methodology. You will not give suggestions on clarifying questions , let them ask their own question.
3. Give Only Relevant , Shorter and required answers to clarifying Questions, nothing like -That's a good clarifying question , just give answer, Keep Answers/Clarifying questions around India Only wherver region/ Place not mentioned.
4. Once Clarifying Questions are done, candidate will start his/her approach.
5. Ask or Challenge with Relevant Questions for their assumptions,  calculations, reasoning and filters for segementation they are using,  If necessary.
6. Don't Suggest Next Filters of calculations, Let candidate do their own thing.
7. Once Candidate is done, You will Give review of their approach - the mistakes in assumptions , the filters that they missed and Improvements that could be done.


Example interview patterns from real interviews -:
"""
        # Add example exchanges from the training data
        for interview in self.interview_data['interviews'][:2]:
            prompt += f"\nExample for {interview['topic']}:\n"
            for exchange in interview['exchanges'][:20]:
                prompt += f"{exchange['role'].title()}: {exchange['content']}\n"
        
        return prompt
    
    def select_problem(self) -> str:
        """Select a random problem statement or create a new one From following, You don't have to necessarily choose these , you can make on your own also"""
        return random.choice(self.interview_data['problem_statements'])
    
    def start_interview(self) -> str:
        """Start a new interview with a problem statement"""
        self.conversation_history = []
        self.current_problem = self.select_problem()
        return f"Your problem statement is to {self.current_problem}. Please feel free to ask any clarifying questions before you begin."
    
    def conduct_interview(self, candidate_response: str) -> str:
        """Conduct one turn of the guesstimate interview"""
        
        # Add candidate's response to history
        self.conversation_history.append({
            "role": "user",
            "content": candidate_response
        })
        
        # Create messages for API call - update format
        messages = []
        
        # Add current problem context if exists
        if self.current_problem:
            messages.append({
                "role": "assistant",
                "content": f"Current estimation problem: {self.current_problem}"
            })
        
        # Add conversation history
        messages.extend([
            {"role": "user" if msg["role"] == "user" else "assistant", "content": msg["content"]}
            for msg in self.conversation_history
        ])
        
        # Get response from Claude - note the updated API format
        response = self.client.messages.create(
            model="claude-3-5-sonnet-20241022",
            messages=messages,
            system=self.system_prompt,  # system is now a separate parameter
            max_tokens=1024,
            temperature=0.7
        )
        
        # Add Claude's response to history
        self.conversation_history.append({
            "role": "assistant",
            "content": response.content[0].text
        })
        
        return response.content[0].text
    
    def evaluate_candidate(self) -> Dict:
        """Evaluate the candidate's guesstimate approach"""
        evaluation_prompt = """Based on the interview conversation, please evaluate:
            1. 'structure': Did they break down the problem logically. Rate out of 5?
            2. 'assumptions': Were assumptions reasonable and India-specific. Rate out of 5?
            3. 'segmentation': How well did they segment the problem. Rate out of 5?
            4. 'math': Were calculations logical and error-free. Rate out of 5?
            5. 'context': Did they consider context of the problem appropriately. Rate out of 5?
            6. 'filters_missed': (they missed and needed to added in string)
            6. 'key_strengths': (Good poitns in the approach in string) 
            7. 'areas_for_improvement': (Areas in approach to improve in string)
            Keep names of 'Key'  like 'structure', 'assumptions', etc..  in JSON as above only. Format as valid JSON string only. FORMAT AS VALID JSON ONLY. I am Saying this again: RETURN AS JSON FORMAT STRING. """
        
        messages = [
            {
                "role": "user",
                "content": f"Problem: {self.current_problem}\n\nInterview transcript: {json.dumps(self.conversation_history)}\n\n{evaluation_prompt}"
            }
        ]
        
        response = self.client.messages.create(
            model="claude-3-5-sonnet-20241022",
            messages=messages,
            system=self.system_prompt,  # system as separate parameter
            max_tokens=1024,
            temperature=0.3
        )
        evaluation_json={}
        try:
            evaluation_json=json.loads(response.content[0].text)
            return evaluation_json
        except (json.JSONDecodeError, IndexError, AttributeError) as e:
            print(f"Error parsing JSON: {e}")
            return None

    





# def response_generator(response):
#     for sentence in response.split("."):
#         yield sentence + " "
#         SpeakText(sentence)

def response_generator(response):
    for sentence in response.split("."):
        for word in sentence.split(" "):  # Corrected 'split'
            yield word + " "  # Yield each word with a space
            time.sleep(0.05)
        #SpeakText(sentence)  # Speak the entire sentence after yielding words


# # Function to convert text to speech
# def SpeakText(command):
#     # Initialize the engine
#     engine = pyttsx3.init()
#     engine.say(command) 
#     engine.runAndWait()

def save_interview(conversation_history: list, evaluation: dict):
    timestamp = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
    folder_path = "all_interviews_scripts"
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        
    file_name = f"interview_{timestamp}.txt"
    file_path = os.path.join(folder_path, file_name)
    
    with open(file_path, "w") as file:
        file.write("Guesstimate Interview\n")
        file.write(f"Datetime: {timestamp}\n\n")
        for msg in conversation_history:
            role = "Interviewer" if msg["role"] == "assistant" else "Candidate"
            file.write(f"{role}: {msg['content']}\n")
        file.write("\nEvaluation:\n")
        file.write(json.dumps(evaluation, indent=2))
    
    return file_path

def create_score_bar_graph(scores):
    fig = go.Figure(data=[
        go.Bar(
            x=list(scores.keys()),
            y=list(scores.values()),
            marker_color='rgb(26, 118, 255)',
            text=[f"{score}/10" for score in scores.values()],
            textposition='auto',
        )
    ])
    
    fig.update_layout(
        title='Interview Performance Scores',
        yaxis=dict(
            title='Score',
            range=[0, 10],  # Set y-axis range from 0 to 10
            tickmode='linear',
            tick0=0,
            dtick=1,  # Show all integer ticks from 0 to 10
        ),
        xaxis_title='Criteria',
        showlegend=False,
        height=400,
        margin=dict(t=50, l=50, r=50, b=50)
    )
    
    return fig

def main():
    st.set_page_config(page_title="Guesstimate Interview Bot", layout="wide")
    
    st.title("🤖 Guesstimate Interview Assistant")
    
    # Initialize session state
    if 'messages' not in st.session_state:
        st.session_state.messages = []
    if 'interview_started' not in st.session_state:
        st.session_state.interview_started = False
    if 'evaluation_done' not in st.session_state:
        st.session_state.evaluation_done = False
    if 'chatbot' not in st.session_state:
        st.session_state.chatbot = None
        
    # Sidebar for API key and controls
    with st.sidebar:
        st.header("Configuration")
        api_key = st.text_input("Enter Anthropic API Key:", type="password")
        #interview_data_path = st.text_input("Interview Data Path:", value="interview_with_context.json")
        
        if st.button("Start New Interview", disabled=not api_key):
            #st.session_state.chatbot = GuesstimateChatbot(api_key, interview_data_path)
            st.session_state.chatbot = GuesstimateChatbot(api_key)
            st.session_state.messages = []
            st.session_state.interview_started = True
            st.session_state.evaluation_done = False
            
            # Start interview and get initial problem
            initial_message = st.session_state.chatbot.start_interview()
            st.session_state.messages.append({"role": "assistant", "content": initial_message})
            
        if st.button("End Interview & Evaluate", disabled=not st.session_state.interview_started or st.session_state.evaluation_done):
            evaluation = st.session_state.chatbot.evaluate_candidate()
            st.session_state.evaluation = evaluation
            st.session_state.evaluation_done = True
            file_path = save_interview(st.session_state.messages, evaluation)
            st.success(f"Interview saved to: {file_path}")
    
    # Main chat interface
    if st.session_state.interview_started:
        # Display chat messages
        for message in st.session_state.messages:
            role = "🤖 Interviewer" if message["role"] == "assistant" else "👤 Candidate"
            with st.chat_message(message["role"]):
                st.write(f"{message['content']}")
        
        # Chat input
        if not st.session_state.evaluation_done:
            user_input = st.chat_input("Your response...")
            if user_input:
                # Add user message
                st.session_state.messages.append({"role": "user", "content": user_input})
                with st.chat_message("user"):
                    st.write(f"{user_input}")
                # Get interviewer response
                with st.spinner("Interviewer is thinking..."):
                    response = st.session_state.chatbot.conduct_interview(user_input)
                    #response=f"ECHO ECHO : {user_input}"
                    st.session_state.messages.append({"role": "assistant", "content": response})
                    with st.chat_message("assistant"):
                        st.write_stream(response_generator(response))

                st.rerun()
        
        # Display evaluation
        if st.session_state.evaluation_done:
            st.header("Interview Evaluation")
            try:
                eval_data = st.session_state.get("evaluation", {})
                
                # Ensure eval_data is a dictionary
                if not isinstance(eval_data, dict):
                    raise ValueError("Evaluation data is not in the expected format.")

                # Convert scores to a 10-point scale (assuming original scores were out of 5)
                scores = {
                    "Structure": eval_data.get("structure", 0) * 2,
                    "Assumptions": eval_data.get("assumptions", 0) * 2,
                    "Segmentation": eval_data.get("segmentation", 0) * 2,
                    "Math": eval_data.get("math", 0) * 2,
                    "Context": eval_data.get("context", 0) * 2,
                }

                # Display bar graph
                st.plotly_chart(create_score_bar_graph(scores), use_container_width=True)

                # Display detailed feedback
                st.subheader("Detailed Feedback")
                st.write("**Missed Filters:**")
                st.write(eval_data.get("filters_missed", "No data available"))
                st.write("**Key Strengths:**")
                st.write(eval_data.get("key_strengths", "No data available"))
                st.write("**Areas for improvement**")
                st.write(eval_data.get("areas_for_improvement", "No data available"))

            except KeyError as e:
                st.error(f"Missing key in evaluation data: {e}")
            except ValueError as e:
                st.error(f"Invalid evaluation data: {e}")
            except Exception as e:
                st.error(f"An unexpected error occurred: {e}")

            # eval_data = st.session_state.evaluation
            
            # # Convert scores to 10-point scale (assuming original scores were out of 5)
            # scores = {
            #     "Structure": eval_data.get("structure", 0) * 2,
            #     "Assumptions": eval_data.get("assumptions", 0) * 2,
            #     "Segmentation": eval_data.get("segmentation", 0) * 2,
            #     "Math": eval_data.get("math", 0) * 2,
            #     "Context": eval_data.get("context", 0) * 2
            # }
            
            # # Display bar graph
            # st.plotly_chart(create_score_bar_graph(scores), use_container_width=True)
            
            # # Display detailed feedback
            # st.subheader("Detailed Feedback")
            # st.write("**Missed Filters:**")
            # st.write(eval_data.get("filters_missed", ""))
            # st.write("**Key Strengths:**")
            # st.write(eval_data.get("key_strengths", ""))
            # st.write("**Areas for improvement**")
            # st.write(eval_data.get("areas_for_improvement", ""))

if __name__ == "__main__":
    main()